<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            // Fruits
            [
                'productID' => 'P001',
                'productName' => 'Apple',
                'productDescription' => 'Fresh red apples from the farm.',
                'price' => 120,
                'quantity' => 200,
                'brand' => 'Organic Farms',
                'categoryID' => 'C001',
                'cartID' => null,
                'image' => 'storage/images/apple.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P002',
                'productName' => 'Banana',
                'productDescription' => 'Sweet and ripe bananas.',
                'price' => 60,
                'quantity' => 300,
                'brand' => 'Tropical Fruits',
                'categoryID' => 'C001',
                'cartID' => null,
                'image' => 'storage/images/banana.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P003',
                'productName' => 'Grapes',
                'productDescription' => 'Juicy green grapes.',
                'price' => 150,
                'quantity' => 180,
                'brand' => 'Vineyard Fresh',
                'categoryID' => 'C001',
                'cartID' => null,
                'image' => 'storage/images/grapes.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vegetables
            [
                'productID' => 'P004',
                'productName' => 'Carrots',
                'productDescription' => 'Crunchy and healthy carrots.',
                'price' => 80,
                'quantity' => 150,
                'brand' => 'Fresh Greens',
                'categoryID' => 'C002',
                'cartID' => null,
                'image' => 'storage/images/carrots.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P005',
                'productName' => 'Broccoli',
                'productDescription' => 'Fresh and nutritious broccoli.',
                'price' => 100,
                'quantity' => 120,
                'brand' => 'Green Farm',
                'categoryID' => 'C002',
                'cartID' => null,
                'image' => 'storage/images/broccoli.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P006',
                'productName' => 'Spinach',
                'productDescription' => 'Fresh organic spinach.',
                'price' => 90,
                'quantity' => 200,
                'brand' => 'Organic Farms',
                'categoryID' => 'C002',
                'cartID' => null,
                'image' => 'storage/images/spinach.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Dairy Products
            [
                'productID' => 'P007',
                'productName' => 'Milk',
                'productDescription' => 'Pure fresh milk from dairy farms.',
                'price' => 200,
                'quantity' => 100,
                'brand' => 'Dairy Best',
                'categoryID' => 'C003',
                'cartID' => null,
                'image' => 'storage/images/milk.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P008',
                'productName' => 'Cheese',
                'productDescription' => 'Rich and creamy cheese.',
                'price' => 300,
                'quantity' => 80,
                'brand' => 'Cheesy Delight',
                'categoryID' => 'C003',
                'cartID' => null,
                'image' => 'storage/images/cheese.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P009',
                'productName' => 'Yogurt',
                'productDescription' => 'Smooth and creamy yogurt.',
                'price' => 150,
                'quantity' => 150,
                'brand' => 'Dairy Best',
                'categoryID' => 'C003',
                'cartID' => null,
                'image' => 'storage/images/yogurt.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Bakery
            [
                'productID' => 'P010',
                'productName' => 'Cake',
                'productDescription' => 'Delicious and moist chocolate cake.',
                'price' => 500,
                'quantity' => 50,
                'brand' => 'Sweet Bakes',
                'categoryID' => 'C004',
                'cartID' => null,
                'image' => 'storage/images/cake.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P011',
                'productName' => 'Croissant',
                'productDescription' => 'Flaky and buttery croissant.',
                'price' => 150,
                'quantity' => 100,
                'brand' => 'Bakery House',
                'categoryID' => 'C004',
                'cartID' => null,
                'image' => 'storage/images/croissant.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P012',
                'productName' => 'Brown Bread',
                'productDescription' => 'Healthy whole grain brown bread.',
                'price' => 200,
                'quantity' => 75,
                'brand' => 'Healthy Bakery',
                'categoryID' => 'C004',
                'cartID' => null,
                'image' => 'storage/images/brown_bread.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Snacks
            [
                'productID' => 'P013',
                'productName' => 'Potato Chips',
                'productDescription' => 'Crunchy and salty potato chips.',
                'price' => 150,
                'quantity' => 300,
                'brand' => 'Crispy Snacks',
                'categoryID' => 'C005',
                'cartID' => null,
                'image' => 'storage/images/chips.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P014',
                'productName' => 'Cookies',
                'productDescription' => 'Delicious, Fresh cookies.',
                'price' => 120,
                'quantity' => 250,
                'brand' => 'Sweet Treats',
                'categoryID' => 'C005',
                'cartID' => null,
                'image' => 'storage/images/cookies.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P015',
                'productName' => 'Popcorn',
                'productDescription' => 'Light and fluffy popcorn.',
                'price' => 100,
                'quantity' => 400,
                'brand' => 'Movie Munchies',
                'categoryID' => 'C005',
                'cartID' => null,
                'image' => 'storage/images/popcorn.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Meat and Poultry
            [
                'productID' => 'P016',
                'productName' => 'Chicken Breast',
                'productDescription' => 'Fresh and tender chicken breast.',
                'price' => 500,
                'quantity' => 120,
                'brand' => 'Farm Fresh',
                'categoryID' => 'C006',
                'cartID' => null,
                'image' => 'storage/images/chicken_breast.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P017',
                'productName' => 'Ground Beef',
                'productDescription' => 'Quality ground beef for your meals.',
                'price' => 600,
                'quantity' => 80,
                'brand' => 'Meat Masters',
                'categoryID' => 'C006',
                'cartID' => null,
                'image' => 'storage/images/ground_beef.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P018',
                'productName' => 'Turkey',
                'productDescription' => 'Fresh whole turkey for special occasions.',
                'price' => 1200,
                'quantity' => 30,
                'brand' => 'Poultry Pride',
                'categoryID' => 'C006',
                'cartID' => null,
                'image' => 'storage/images/turkey.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Seafood
            [
                'productID' => 'P019',
                'productName' => 'Salmon Fillet',
                'productDescription' => 'Fresh salmon fillet, rich in omega-3.',
                'price' => 800,
                'quantity' => 50,
                'brand' => 'Seafood Delight',
                'categoryID' => 'C007',
                'cartID' => null,
                'image' => 'storage/images/salmon.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P020',
                'productName' => 'Shrimp',
                'productDescription' => 'Fresh shrimp, perfect for grilling.',
                'price' => 1000,
                'quantity' => 60,
                'brand' => 'Ocean Catch',
                'categoryID' => 'C007',
                'cartID' => null,
                'image' => 'storage/images/shrimp.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P021',
                'productName' => 'Tuna',
                'productDescription' => 'Fresh tuna Fish.',
                'price' => 400,
                'quantity' => 150,
                'brand' => 'Tuna Best',
                'categoryID' => 'C007',
                'cartID' => null,
                'image' => 'storage/images/tuna.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Beverages
            [
                'productID' => 'P022',
                'productName' => 'Coca-Cola',
                'productDescription' => 'Refreshing soft drink.',
                'price' => 150,
                'quantity' => 200,
                'brand' => 'Coca-Cola',
                'categoryID' => 'C008',
                'cartID' => null,
                'image' => 'storage/images/coca_cola.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P023',
                'productName' => 'Orange Juice',
                'productDescription' => 'Freshly squeezed orange juice.',
                'price' => 200,
                'quantity' => 180,
                'brand' => 'Fresh Squeezed',
                'categoryID' => 'C008',
                'cartID' => null,
                'image' => 'storage/images/orange_juice.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P024',
                'productName' => 'Green Tea',
                'productDescription' => 'Organic green tea leaves.',
                'price' => 250,
                'quantity' => 220,
                'brand' => 'Tea Leaf',
                'categoryID' => 'C008',
                'cartID' => null,
                'image' => 'storage/images/green_tea.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Condiments and Spices
            [
                'productID' => 'P025',
                'productName' => 'Ketchup',
                'productDescription' => 'Tomato ketchup for dipping.',
                'price' => 120,
                'quantity' => 200,
                'brand' => 'Saucy Goodness',
                'categoryID' => 'C009',
                'cartID' => null,
                'image' => 'storage/images/ketchup.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P026',
                'productName' => 'Olive Oil',
                'productDescription' => 'Extra virgin olive oil for cooking.',
                'price' => 600,
                'quantity' => 100,
                'brand' => 'Pure Oils',
                'categoryID' => 'C009',
                'cartID' => null,
                'image' => 'storage/images/olive_oil.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P027',
                'productName' => 'Black Pepper',
                'productDescription' => 'Ground black pepper for seasoning.',
                'price' => 80,
                'quantity' => 250,
                'brand' => 'Spice King',
                'categoryID' => 'C009',
                'cartID' => null,
                'image' => 'storage/images/black_pepper.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Frozen Foods
            [
                'productID' => 'P028',
                'productName' => 'Frozen Pizza',
                'productDescription' => 'Delicious frozen Raspberries.',
                'price' => 900,
                'quantity' => 80,
                'brand' => 'Pizza Delight',
                'categoryID' => 'C010',
                'cartID' => null,
                'image' => 'storage/images/raspberry.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P029',
                'productName' => 'Frozen Vegetables',
                'productDescription' => 'Mixed frozen vegetables.',
                'price' => 300,
                'quantity' => 120,
                'brand' => 'Frozen Farm',
                'categoryID' => 'C010',
                'cartID' => null,
                'image' => 'storage/images/frozen_vegetables.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P030',
                'productName' => 'Frozen Desserts',
                'productDescription' => 'Assorted frozen desserts.',
                'price' => 600,
                'quantity' => 90,
                'brand' => 'Sweet Treats',
                'categoryID' => 'C010',
                'cartID' => null,
                'image' => 'storage/images/frozen_desserts.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Health and Beauty
            [
                'productID' => 'P031',
                'productName' => 'Shampoo',
                'productDescription' => 'Organic shampoo for healthy hair.',
                'price' => 350,
                'quantity' => 100,
                'brand' => 'Hair Care',
                'categoryID' => 'C011',
                'cartID' => null,
                'image' => 'storage/images/shampoo.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P032',
                'productName' => 'Moisturizer',
                'productDescription' => 'Hydrating moisturizer for all skin types.',
                'price' => 500,
                'quantity' => 80,
                'brand' => 'Beauty Essentials',
                'categoryID' => 'C011',
                'cartID' => null,
                'image' => 'storage/images/moisturizer.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P033',
                'productName' => 'Toothpaste',
                'productDescription' => 'Whitening toothpaste for bright smiles.',
                'price' => 200,
                'quantity' => 150,
                'brand' => 'Bright Smile',
                'categoryID' => 'C011',
                'cartID' => null,
                'image' => 'storage/images/toothpaste.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Household Items
            [
                'productID' => 'P034',
                'productName' => 'Laundry Detergent',
                'productDescription' => 'Powerful detergent for clean clothes.',
                'price' => 600,
                'quantity' => 100,
                'brand' => 'Clean & Fresh',
                'categoryID' => 'C012',
                'cartID' => null,
                'image' => 'storage/images/laundry_detergent.jpg',
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P035',
                'productName' => 'Dish Soap',
                'productDescription' => 'Effective hand sanitizers.',
                'price' => 300,
                'quantity' => 150,
                'brand' => 'Sparkling Clean',
                'categoryID' => 'C012',
                'cartID' => null,
                'image' => 'storage/images/hand_sanitizer.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productID' => 'P036',
                'productName' => 'Paper Towels',
                'productDescription' => 'Strong and absorbent paper towels.',
                'price' => 250,
                'quantity' => 200,
                'brand' => 'Home Essentials',
                'categoryID' => 'C012',
                'cartID' => null,
                'image' => 'storage/images/paper_towels.jpg',
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
